version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-west-2
    ECR_REPO_URI: 001520131116.dkr.ecr.eu-west-2.amazonaws.com
    CONTAINER_NAME: TandG

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

      - echo Getting Git commit hash...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - echo Image tag will be $COMMIT_HASH
      - IMAGE_URI=$ECR_REPO_URI:$COMMIT_HASH

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_URI

      - echo Creating imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json

      - echo Build completed successfully
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json